### ISSUE TITLE
Deployment header broken

### ISSUE THREAD

**Issue by Ellipse0934** [farkon00/binarian#7]
On my browser I see: 
![image](https://github.com/farkon00/binarian/assets/7466364/3d481931-e12a-4abb-8fbe-fedc1df2ec7a)

**Comment by farkon00** [comment]
What browser were you using?

**Comment by Ellipse0934** [comment]
Firefox 115.0 (64-bit)

**Comment by farkon00** [comment]
Fixed by [commit 001358f in the website repo](https://github.com/farkon00/bino-web/commit/001358fd7e4732668ecaf8040ff37409810d725b)

**Comment by Ellipse0934** [comment]
POGOMEGA!!!!!!
